# Generated by Django 4.1.1 on 2023-02-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
