# Generated by Django 4.1.1 on 2023-02-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_bill_invoice_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
