# Generated by Django 4.1.1 on 2023-02-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_customer_first_name_alter_customer_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='sum_total',
            field=models.FloatField(default=0),
        ),
    ]
